name: alba
description: Alba is a framework that boosts Flutter project development.
version: 0.0.19
homepage: https://github.com/alba-framework/alba
repository: https://github.com/alba-framework/alba
issue_tracker: https://github.com/alba-framework/alba/issues
documentation: https://alba-framework.github.io/

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  meta: ^1.7.0
  path: ^1.8.0
  path_to_regexp: ^0.4.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.12
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
