name: alba
description: Boost your Flutter development.
version: 0.0.1
homepage: https://github.com/mariomka/alba
repository: https://github.com/mariomka/alba
issue_tracker: https://github.com/mariomka/alba/issues

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_to_regexp: ^0.4.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: